# Generated by Django 3.0.2 on 2021-08-07 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_book',
            name='pattern',
        ),
        migrations.RemoveField(
            model_name='school_book',
            name='standard',
        ),
        migrations.RemoveField(
            model_name='school_list',
            name='model_name',
        ),
    ]
