# Generated by Django 3.0.2 on 2021-08-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210808_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_book',
            name='pattern',
            field=models.CharField(default='MSBT', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school_book',
            name='standard',
            field=models.CharField(default='10th', max_length=50),
            preserve_default=False,
        ),
    ]
